# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1acfe26753aa6bc9f660e0beccb13837688a77bbcf052d0f1934b3092b32a3b6d4ccf71c7e7a1ac60b72f1dec73baae778c0edb0251bc30035e97e8eb537092

test:
  secret_key_base: 34203c72cb2a46d7f3abdb06e7f06d5f056421549fe0cff9e6ef3f42d5a63df7132f1a346e4a72e83b0601b37e4b52d835f52a109bf0a962ed194b75e48fe651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
