# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
  Unit.new( longitude: "Optional(\"Optional(< 30.03410000,-95.21572600>  /-...", unit_number: "864639473-5", username: "Kristian's iPhone 4", address: "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")").save
  Unit.new( longitude: "Optional(\"Optional(< 30.03410000,-95.21572600>  /-...", unit_number: "C00075569674", username: "Kristian's iPhone 4", address: "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")").save
  Unit.new( longitude: "Optional(\"Optional(< 30.03410000,-95.21572600>  /-...", unit_number: "0020066779283", username: "Kristian's iPhone 4", address: "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")").save
  Unit.new( longitude: "Optional(\"Optional(< 30.03410000,-95.21572600>  /-...", unit_number: "03400908", username: "Kristian's iPhone 4", address: "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")").save
  Unit.new( longitude: "Optional(\"Optional(< 29.94731900,-95.33546200>  /-...", unit_number: "FXWP001", username: "keenan sturtevant’s iPhone", address: "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")").save
  Unit.new( longitude: "Optional(\"Optional(< 29.94731900,-95.33546200>  /-...", unit_number: "FXWP002", username: "keenan sturtevant’s iPhone", address: "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")").save
  Unit.new( longitude: "Optional(\"Optional(< 30.03410000,-95.21572600>  /-...", unit_number: "864639473-5", username: "Kristian's iPhone 4", address: "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")").save
  Unit.new( longitude: "Optional(\"Optional(< 30.03410000,-95.21572600>  /-...", unit_number: "C00075569674", username: "Kristian's iPhone 4", address: "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")").save
  Unit.new( longitude: "Optional(\"Optional(< 30.03410000,-95.21572600>  /-...", unit_number: "0020066779283", username: "Kristian's iPhone 4", address: "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")").save
  Unit.new( longitude: "Optional(\"Optional(< 30.03410000,-95.21572600>  /-...", unit_number: "03400908", username: "Kristian's iPhone 4", address: "Optional(\"Optional([SubAdministrativeArea: Harris, CountryCode: US, SubLocality: IAH Airport Area, State: TX, Street: 3340 Greens Rd, ZIP: 77032, Name: 3340 Greens Rd, Thoroughfare: Greens Rd, FormattedAddressLines: (\\n    \\\"3340 Greens Rd\\\",\\n    \\\"Houston, TX  77032\\\",\\n    \\\"United States\\\"\\n), SubThoroughfare: 3340, PostCodeExtension: 2369, Country: United States, City: Houston])\")").save
  Unit.new( longitude: "Optional(\"Optional(< 29.94731900,-95.33546200>  /-...", unit_number: "FXWP001", username: "keenan sturtevant’s iPhone", address: "Optional([FormattedAddressLines: (\n    \"5711 Spring Lodge Dr\",\n    \"Kingwood, TX  77345\",\n    \"United States\"\n), Street: 5711 Spring Lodge Dr, SubAdministrativeArea: Harris, Thoroughfare: Spring Lodge Dr, ZIP: 77345, Name: 5711 Spring Lodge Dr, City: Houston, PostCodeExtension: 1470, Country: United States, State: TX, SubLocality: Kingwood, SubThoroughfare: 5711, CountryCode: US])").save
  Unit.new( longitude: "Optional(\"Optional(< 29.94731900,-95.33546200>  /-...", unit_number: "FXWP002", username: "keenan sturtevant’s iPhone", address: "Optional([FormattedAddressLines: (\n    \"5711 Spring Lodge Dr\",\n    \"Kingwood, TX  77345\",\n    \"United States\"\n), Street: 5711 Spring Lodge Dr, SubAdministrativeArea: Harris, Thoroughfare: Spring Lodge Dr, ZIP: 77345, Name: 5711 Spring Lodge Dr, City: Houston, PostCodeExtension: 1470, Country: United States, State: TX, SubLocality: Kingwood, SubThoroughfare: 5711, CountryCode: US])").save